### ISSUE TITLE
Why hashes on day2 `in-bounds?` function?

### ISSUE THREAD

**Issue by chrismurrph** [bhauman/advent-of-clojure-2016#1]
(defn in-bounds? [[x y]]
      (and #(<= -1 x 1) #(<= -1 y 1)))

Works without the hashes:

    (defn in-bounds? [[x y]]
      (and (<= -1 x 1) (<= -1 y 1)))

**Comment by bhauman** [comment]
Thanks! I fixed that must have forgot to push it.

**Comment by bhauman** [comment]
sorry for any confusion that may have caused

**Comment by chrismurrph** [comment]
Some small confusion for a few moments. I'm going through your answers starting at the beginning. And so far the enlightenment has been more than worth any confusion: plenty of improved approaches for me to pick up. 
I might even put in the odd sneaky PR if that's okay. Only for something that's a pretty obvious improvement. One thing I'm thinking is to get rid of `partial` and instead have a closed over higher order function.
